// 模块清单 — 单一事实来源 (single source of truth)
//
// 本文件由 scripts/generate-modules.mjs 自动生成，请勿手动编辑。
// 新增 / 删除模块后运行:
//   node scripts/generate-modules.mjs
// ModuleLoader.bootstrap() 会按此顺序注入（经典脚本，兼容 file:// 直接打开）。
window.SNAKE_MODULE_MANIFEST = [
  'account',
  'achievement_detail',
  'achievement_preview',
  'achievement_search',
  'achievement_showcase',
  'achievement_stats',
  'achievement_toast',
  'achievements_manager',
  'ai_engine_selector',
  'ai_player',
  'best_manager',
  'challenge',
  'churn_analytics',
  'churn_warning',
  'codex_manager',
  'daily_challenge_mode',
  'daily_rewards',
  'daily_tasks',
  'endgame_flow',
  'enhanced_newbie_guide',
  'enhanced_return_rewards',
  'events',
  'first_milestone',
  'friends',
  'friends_challenge',
  'friends_leaderboard',
  'guide',
  'in_game_hints',
  'in_game_notifications',
  'input',
  'item_spawn',
  'leaderboard',
  'level_unlock',
  'loop_timers',
  'mode_rules',
  'mode_trial',
  'modes',
  'multiplayer',
  'personalized_achievements',
  'play_state',
  'profile',
  'purchase_feedback',
  'quick_start',
  'recall',
  'recap',
  'records',
  'render',
  'replay',
  'reset_flow',
  'reset_prepare',
  'return_center',
  'return_missions',
  'return_reminder',
  'returning_guide',
  'reward_preview',
  'reward_system',
  'round_state',
  'round_stats_manager',
  'season',
  'season_rewards_preview',
  'settings',
  'settlement',
  'shop',
  'skill_tree',
  'sound',
  'spectate',
  'statistics',
  'storage',
  'titles',
  'workshop',
  'workshop_runtime'
];

// 懒加载模块 (v1.28.0): 不阻塞游戏启动，就绪后由 bootstrap 后台续注。
window.SNAKE_LAZY_MODULES = [
  'achievement_preview',
  'ai_engine_selector',
  'churn_analytics',
  'churn_warning',
  'enhanced_newbie_guide',
  'enhanced_return_rewards',
  'in_game_hints',
  'personalized_achievements',
  'quick_start',
  'returning_guide',
  'reward_preview',
  'season_rewards_preview',
  'skill_tree'
];
